#@ load("@ytt:data", "data")
#@ load("@ytt:assert", "assert")
---
apiVersion: v1
kind: Secret
metadata:
  name: controller-manager
  namespace: actions-runner-system
stringData:
  github_token: #@ data.values.github_token or assert.fail("'github_token' is required!")